version: "3.9"

services:
  app:
    build:
      dockerfile: ./app/Dockerfile
      context: .
      args:
        - DEV=true
    ports:
      - "8321:8000"
    volumes:
      - ./app:/app
    command: >
     sh -c "python manage.py wait_for_db && 
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./app/.env
    depends_on:
      - db


  db:
    image: postgres:16
    ports:
      - "5321:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    env_file:
      - ./app/.env

  redis:
    image: redis:7.0.5-alpine
    hostname: redis


  worker:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    hostname: worker
    entrypoint: celery
    command: -A celery_folder.celery_app.app worker --loglevel=info
    volumes:
      - ./app:/app
    links:
      - redis
    depends_on:
      - redis

  flower:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    hostname: flower
    entrypoint: celery
    command: -A celery_folder.celery_app.app flower
    volumes:
      - ./app:/app
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"



volumes:
  dev-db-data: