# Generated by Django 5.2.16 on 2026-08-03 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import borrowing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(default=borrowing.models.default_due_date)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='books.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['borrowed_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('returned_at__isnull', True)), fields=('book', 'member'), name='unique_active_loan')],
            },
        ),
    ]
