# Generated by Django 4.2 on 2024-09-04 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_member_borrowrecord_visitor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowrecord',
            old_name='visitor',
            new_name='member',
        ),
    ]
